//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanoBin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NanoBin.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle bin Auto Cleaned ({0} MB).
        /// </summary>
        internal static string baloonAutoCleaned {
            get {
                return ResourceManager.GetString("baloonAutoCleaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle bin Manually cleaned ({0} MB).
        /// </summary>
        internal static string baloonManuallyCleaned {
            get {
                return ResourceManager.GetString("baloonManuallyCleaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} — {1} Files, {2} MB.
        /// </summary>
        internal static string byDriveString {
            get {
                return ResourceManager.GetString("byDriveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete File(s).
        /// </summary>
        internal static string captionDeleteElements {
            get {
                return ResourceManager.GetString("captionDeleteElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permanently delete {0} item(s)?.
        /// </summary>
        internal static string confirmDeleteElements {
            get {
                return ResourceManager.GetString("confirmDeleteElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoCleaning asks no confirmation!.
        /// </summary>
        internal static string logAutoCleanEnabled {
            get {
                return ResourceManager.GetString("logAutoCleanEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Recycle bin Auto Cleaned ({1} MB).
        /// </summary>
        internal static string logBinAutoCleaned {
            get {
                return ResourceManager.GetString("logBinAutoCleaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Recycle bin Manually cleaned ({1} MB).
        /// </summary>
        internal static string logBinManuallyCleaned {
            get {
                return ResourceManager.GetString("logBinManuallyCleaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could Not open Recycle Bin:.
        /// </summary>
        internal static string msgCouldNotOpenBin {
            get {
                return ResourceManager.GetString("msgCouldNotOpenBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files: {0}, Size: {1} MB.
        /// </summary>
        internal static string StatusLabel {
            get {
                return ResourceManager.GetString("StatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle bin is empty on all drives.
        /// </summary>
        internal static string strAllbinsAreEmpty {
            get {
                return ResourceManager.GetString("strAllbinsAreEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another instance of program is already running!.
        /// </summary>
        internal static string strAnotherInstanceRunning {
            get {
                return ResourceManager.GetString("strAnotherInstanceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string strERROR {
            get {
                return ResourceManager.GetString("strERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files: {0}{1}Size: {2} MB.
        /// </summary>
        internal static string strNotifyIconText {
            get {
                return ResourceManager.GetString("strNotifyIconText", resourceCulture);
            }
        }
    }
}
