name: test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - 'LICENSE'
      - '**/*.ico'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.svg'

jobs:
  build:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: 🧾 Checkout repository
        uses: actions/checkout@v4
        
      - name: 🔍 Extract version from AssemblyInfo.cs
        id: get_version
        shell: powershell
        run: |
          $line = Select-String -Path ./Properties/AssemblyInfo.cs -Pattern 'AssemblyVersion\("([0-9\.]+)"\)'
          if ($line.Matches.Count -eq 0) {
          Write-Error "AssemblyVersion not found!"
          }
          $version = $line.Matches[0].Groups[1].Value
          Write-Host "Version: $version"
              

