name: test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - 'LICENSE'
      - '**/*.ico'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.svg'

jobs:
  build:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: 🧾 Checkout repository
        uses: actions/checkout@v4
        
      - name: 🔍 Extract version from AssemblyInfo.cs
        id: get_version
        shell: pwsh
        run: |
          $content = Get-Content ./Properties/AssemblyInfo.cs
          Write-Host $content
          Write-Host "----------------------------------------------------------------------"
          Write-Host "Getting matches..."
            if ($content -cmatch '(AssemblyVersion)') {
                Write-Host "$matches"

              }
              else
              {
            Write-Host "No matches"
              
              }
              

