name: test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - 'LICENSE'
      - '**/*.ico'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.svg'

jobs:
  build:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:

      - name: 🔍 Extract version from AssemblyInfo.cs
        id: get_version
        shell: pwsh
        run: |
          $content = Get-Content ./Properties/AssemblyInfo.cs
            if ($content -match 'AssemblyVersion\("([0-9\.]+)"\)') {
                Write-Host $matches

              }

